logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: spring.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR

server:
  port: 38195