spring:
  profiles:
    active: @profiles.active@
logging:
  config: classpath:logback-spring.xml
  path: logs
  file: bts-zaful-report.log
  level:
    root: info
    org.springframework: ERROR
---
spring:
  profiles: test
  hbase:
    zkServers: 172.31.61.192:2181,172.31.62.7:2181,172.31.59.31:2181,172.31.62.153:2181,172.31.36.227:2181,172.31.40.73:2181
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-dimensions_zafu_recommend
    producer:
      client-id: bts-zaful-log
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092


app:
  kafka:
    log-json-topic: dy_zaful_bury_source_data
    log-output-topic: dy_bts_report_recommend_zaful
    log-zaful-out-topic: dy_bts_zaful_re_simple_report
    zaful-list-page-topic: dy_bts_zaful_list_page_report

server:
  port: 38086

---
spring:
  profiles: prod
  hbase:
    zkServers: bts-master:2181,bts-masterbak:2181,bts-datanode01:2181,bts-datanode02:2181,bts-datanode03:2181,bts-datanode04:2181
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-dimensions_zafu_recommend
    producer:
      client-id: bts-zaful-log
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092
    listener:
      concurrency: 10

app:
  kafka:
    log-source-topic: glbg-analitic
    log-json-topic: dy_zaful_bury_source_data
    log-output-topic: dy_bts_report_recommend_zaful
    log-zaful-out-topic: dy_bts_zaful_re_simple_report
    zaful-list-page-topic: dy_bts_zaful_list_page_report

server:
  port: 38086