spring:
  profiles:
    #active: dev
    active: @profiles.active@
    #active: pressure-test
logging:
  #config: classpath:logback.xml
  path: logs
  file: logs/dy-realtime-data-query-service.log
  level:
    root: info
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] %logger{50} - %msg%n'
#server:
#  undertow:
#    io-threads: 256
#    worker-threads: 2048
#  compression:
#    enabled: false
---
spring:
  profiles: dev
  application:
    name: dy-realtime-data-query-service-dev
  cloud:
    sentinel:
      transport:
        dashboard: localhost:38194
      eager: true

server:
  port: 38193


---
spring:
  profiles: prod
  application:
    name: dy-realtime-data-query-service-prod
server:
  port: 38193

app:
  cron:
    fbad-freatrue: 0 30 * * * ?
    zaful-app-user-fb-freatrue: 0 30 1 * * ?

