package com.globalegrow.mapper.bts;

import com.globalegrow.model.bts.BtsResult;
import com.globalegrow.model.bts.BtsResultExample;
import org.apache.ibatis.annotations.Param;

public interface BtsResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int deleteByExample(BtsResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int deleteByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int insert(BtsResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int insertSelective(BtsResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    BtsResult selectByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") BtsResult record, @Param("example") BtsResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int updateByExample(@Param("record") BtsResult record, @Param("example") BtsResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int updateByPrimaryKeySelective(BtsResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bts_plan_result
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    int updateByPrimaryKey(BtsResult record);
}