spring:
  profiles:
    active: dev
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: logs/bts-common-report.log
  level:
    root: info
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
    com.jayway: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] %logger{50} - %msg%n'
server:
  undertow:
    io-threads: 128
    worker-threads: 1024
  compression:
    enabled: false
---
spring:
  profiles: dev

server:
  port: 38195

---
spring:
  profiles: prod
server:
  port: 38195