spring:
  profiles:
    active: @profiles.active@
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: logs/bts-common-report.log
  level:
    root: info
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
    com.jayway: ERROR
    org.springframework.kafka: ERROR
    org.apache.kafka: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] %logger{50} - %msg%n'
server:
  undertow:
    io-threads: 128
    worker-threads: 1024
  compression:
    enabled: false
---
spring:
  profiles: dev
  hbase:
    zkServers:192.168.211.200:2181,192.168.211.201:2181,192.168.211.202:2181
  elasticsearch:
    #正式环境本地连接用外网地址不然连接不上，上线用内网地址
    jest:
      uris[0]: http://54.144.128.124:9202
      uris[1]: http://100.26.77.0:9202
      uris[2]: http://100.26.74.93:9202
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  kafka:
    #测试kafka，外网ip
    #bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092
    #bootstrap-servers: 52.21.158.25:9092,54.156.168.17:9092,34.235.224.156:9092
    bootstrap-servers: 192.168.211.200:9092,192.168.211.201:9092,192.168.211.202:9092

    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: mysql-bin-log-zaful-common-report-dev
  redis:
    #测试地址，外网ip
    timeout: 86400
    password: 6e1KWyC29w
    cluster:
      nodes[0]: 192.168.211.200:6380
      nodes[1]: 192.168.211.200:6381
      nodes[2]: 192.168.211.201:6380
      nodes[3]: 192.168.211.201:6381
      nodes[4]: 192.168.211.202:6380
      nodes[5]: 192.168.211.202:6381

#    sentinel:
#      master: mymaster
#      nodes: 172.31.19.189:26380,172.31.19.189:26381,172.31.19.189:26382

dy_bts_zaful_report_order: dy_bts_zaful_report_order_dev
dy_bts_gb_report_order: dy_bts_gb_report_order_dev

server:
  port: 38195

---
spring:
  profiles: prod
  hbase:
    zkServers: 172.31.61.192:2181,172.31.62.7:2181,172.31.59.31:2181,172.31.62.153:2181,172.31.36.227:2181,172.31.40.73:2181
  elasticsearch:
    jest:
      uris[0]: http://172.31.43.158:9202
      uris[1]: http://172.31.47.84:9202
      uris[2]: http://172.31.55.231:9202
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  kafka:
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: mysql-bin-log-zaful-common-report
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    cluster:
      nodes[0]: 172.31.47.78:6382
      nodes[1]: 172.31.47.222:6380
      nodes[2]: 172.31.47.222:6381
      nodes[3]: 172.31.44.253:6379
      nodes[4]: 172.31.44.253:6380
      nodes[5]: 172.31.47.78:6383

dy_bts_zaful_report_order: dy_bts_zaful_report_order_dev
dy_bts_gb_report_order: dy_bts_gb_report_order_dev

app:
  order:
    zaful:
      seconds: 604800
    gb:
      seconds: 604800



server:
  port: 38195

#redis:
#  type: cluster
#  nodes: redis://172.31.47.78:6382,redis://172.31.47.222:6380,redis://172.31.47.222:6381,redis://172.31.44.253:6379,redis://172.31.44.253:6380,redis://172.31.47.78:6383
#  password: 6e1KWyC29w