package com.globalegrow.model.zaful;

public class OrderInfoWithBLOBs extends OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.postscript
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String postscript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.aff_extra
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String affExtra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.postscript
     *
     * @return the value of eload_order_info.postscript
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPostscript() {
        return postscript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.postscript
     *
     * @param postscript the value for eload_order_info.postscript
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPostscript(String postscript) {
        this.postscript = postscript == null ? null : postscript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.aff_extra
     *
     * @return the value of eload_order_info.aff_extra
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getAffExtra() {
        return affExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.aff_extra
     *
     * @param affExtra the value for eload_order_info.aff_extra
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAffExtra(String affExtra) {
        this.affExtra = affExtra == null ? null : affExtra.trim();
    }
}