package com.globalegrow.model.zaful;

public class OrderGoodsWithBLOBs extends OrderGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_attr
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String goodsAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.custom_size
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String customSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_attr
     *
     * @return the value of eload_order_goods.goods_attr
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_attr
     *
     * @param goodsAttr the value for eload_order_goods.goods_attr
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr == null ? null : goodsAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.custom_size
     *
     * @return the value of eload_order_goods.custom_size
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getCustomSize() {
        return customSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.custom_size
     *
     * @param customSize the value for eload_order_goods.custom_size
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCustomSize(String customSize) {
        this.customSize = customSize == null ? null : customSize.trim();
    }
}