package com.globalegrow.model.zaful;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_node
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte payNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_group_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer orderGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_suffix
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Short orderSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.user_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_status
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.consignee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.country
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Short country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.province
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.city
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.address
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.address2
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.zipcode
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.id_card
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.tel
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.email
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.shipping_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte shippingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.shipping_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String shippingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.shipping_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String shippingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.Tracking_NO
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String trackingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String payName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.yuan_goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal yuanGoodsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal goodsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.coupon_discount_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal couponDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal shippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal freeShippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.insure_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal insureFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.formalities_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal formalitiesFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal payFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.multi_order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal multiOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_currency
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String orderCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal orderRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.realpay
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal realpay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String referer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.add_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.shipping_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer shippingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.cancel_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_note
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String payNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.tax
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.Invoice
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean invoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.promotion_code_youhuilv
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String promotionCodeYouhuilv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.promotion_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String promotionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.Need_Traking_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal needTrakingNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer wjLinkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer isDao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_ping
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer isPing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.used_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Float usedPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.point_money
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Float pointMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_login
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte isLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_to_erp
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean isToErp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.wj_referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String wjReferer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean orderMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_display_track_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean isDisplayTrackGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.com_is_fa
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean comIsFa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.com_fa_date
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer comFaDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.full_reduce_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal fullReduceDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.buytype
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean buytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.lang
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String lang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_ip
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String payIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_to_oms
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean isToOms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.used_wallet
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal usedWallet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_order_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean isOrderReview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.is_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte isPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.tax_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.recieved_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer recievedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.media_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String mediaSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.campagin
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String campagin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.oms_release_storage
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean omsReleaseStorage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.cod_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal codDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.cod_orientation
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean codOrientation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.order_class
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean orderClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.retargeting
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String retargeting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String campaign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.version
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.date_wj_linkid_created
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer dateWjLinkidCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.postback_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String postbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pic_url
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.user_wish_refund
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean userWishRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.pay_platform
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean payPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.add_to_cart
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean addToCart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.aff_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String affSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.utm_campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String utmCampaign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.utm_medium
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String utmMedium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_info.buy_from
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean buyFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_id
     *
     * @return the value of eload_order_info.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_id
     *
     * @param orderId the value for eload_order_info.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_node
     *
     * @return the value of eload_order_info.pay_node
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getPayNode() {
        return payNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_node
     *
     * @param payNode the value for eload_order_info.pay_node
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayNode(Byte payNode) {
        this.payNode = payNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_group_id
     *
     * @return the value of eload_order_info.order_group_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getOrderGroupId() {
        return orderGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_group_id
     *
     * @param orderGroupId the value for eload_order_info.order_group_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderGroupId(Integer orderGroupId) {
        this.orderGroupId = orderGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_sn
     *
     * @return the value of eload_order_info.order_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_sn
     *
     * @param orderSn the value for eload_order_info.order_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_suffix
     *
     * @return the value of eload_order_info.order_suffix
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Short getOrderSuffix() {
        return orderSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_suffix
     *
     * @param orderSuffix the value for eload_order_info.order_suffix
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderSuffix(Short orderSuffix) {
        this.orderSuffix = orderSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.user_id
     *
     * @return the value of eload_order_info.user_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.user_id
     *
     * @param userId the value for eload_order_info.user_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_status
     *
     * @return the value of eload_order_info.order_status
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_status
     *
     * @param orderStatus the value for eload_order_info.order_status
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.consignee
     *
     * @return the value of eload_order_info.consignee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.consignee
     *
     * @param consignee the value for eload_order_info.consignee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.country
     *
     * @return the value of eload_order_info.country
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Short getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.country
     *
     * @param country the value for eload_order_info.country
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCountry(Short country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.province
     *
     * @return the value of eload_order_info.province
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.province
     *
     * @param province the value for eload_order_info.province
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.city
     *
     * @return the value of eload_order_info.city
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.city
     *
     * @param city the value for eload_order_info.city
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.address
     *
     * @return the value of eload_order_info.address
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.address
     *
     * @param address the value for eload_order_info.address
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.address2
     *
     * @return the value of eload_order_info.address2
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.address2
     *
     * @param address2 the value for eload_order_info.address2
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.zipcode
     *
     * @return the value of eload_order_info.zipcode
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.zipcode
     *
     * @param zipcode the value for eload_order_info.zipcode
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.id_card
     *
     * @return the value of eload_order_info.id_card
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.id_card
     *
     * @param idCard the value for eload_order_info.id_card
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.tel
     *
     * @return the value of eload_order_info.tel
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.tel
     *
     * @param tel the value for eload_order_info.tel
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.email
     *
     * @return the value of eload_order_info.email
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.email
     *
     * @param email the value for eload_order_info.email
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.shipping_id
     *
     * @return the value of eload_order_info.shipping_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.shipping_id
     *
     * @param shippingId the value for eload_order_info.shipping_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingId(Byte shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.shipping_name
     *
     * @return the value of eload_order_info.shipping_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.shipping_name
     *
     * @param shippingName the value for eload_order_info.shipping_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.shipping_method
     *
     * @return the value of eload_order_info.shipping_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.shipping_method
     *
     * @param shippingMethod the value for eload_order_info.shipping_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingMethod(String shippingMethod) {
        this.shippingMethod = shippingMethod == null ? null : shippingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.Tracking_NO
     *
     * @return the value of eload_order_info.Tracking_NO
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getTrackingNo() {
        return trackingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.Tracking_NO
     *
     * @param trackingNo the value for eload_order_info.Tracking_NO
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setTrackingNo(String trackingNo) {
        this.trackingNo = trackingNo == null ? null : trackingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_id
     *
     * @return the value of eload_order_info.pay_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_id
     *
     * @param payId the value for eload_order_info.pay_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_name
     *
     * @return the value of eload_order_info.pay_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_name
     *
     * @param payName the value for eload_order_info.pay_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.yuan_goods_amount
     *
     * @return the value of eload_order_info.yuan_goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getYuanGoodsAmount() {
        return yuanGoodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.yuan_goods_amount
     *
     * @param yuanGoodsAmount the value for eload_order_info.yuan_goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setYuanGoodsAmount(BigDecimal yuanGoodsAmount) {
        this.yuanGoodsAmount = yuanGoodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.goods_amount
     *
     * @return the value of eload_order_info.goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.goods_amount
     *
     * @param goodsAmount the value for eload_order_info.goods_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsAmount(BigDecimal goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.coupon_discount_amount
     *
     * @return the value of eload_order_info.coupon_discount_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getCouponDiscountAmount() {
        return couponDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.coupon_discount_amount
     *
     * @param couponDiscountAmount the value for eload_order_info.coupon_discount_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCouponDiscountAmount(BigDecimal couponDiscountAmount) {
        this.couponDiscountAmount = couponDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.shipping_fee
     *
     * @return the value of eload_order_info.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.shipping_fee
     *
     * @param shippingFee the value for eload_order_info.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.free_shipping_fee
     *
     * @return the value of eload_order_info.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getFreeShippingFee() {
        return freeShippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.free_shipping_fee
     *
     * @param freeShippingFee the value for eload_order_info.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setFreeShippingFee(BigDecimal freeShippingFee) {
        this.freeShippingFee = freeShippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.insure_fee
     *
     * @return the value of eload_order_info.insure_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getInsureFee() {
        return insureFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.insure_fee
     *
     * @param insureFee the value for eload_order_info.insure_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setInsureFee(BigDecimal insureFee) {
        this.insureFee = insureFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.formalities_fee
     *
     * @return the value of eload_order_info.formalities_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getFormalitiesFee() {
        return formalitiesFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.formalities_fee
     *
     * @param formalitiesFee the value for eload_order_info.formalities_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setFormalitiesFee(BigDecimal formalitiesFee) {
        this.formalitiesFee = formalitiesFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_fee
     *
     * @return the value of eload_order_info.pay_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_fee
     *
     * @param payFee the value for eload_order_info.pay_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayFee(BigDecimal payFee) {
        this.payFee = payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_amount
     *
     * @return the value of eload_order_info.order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_amount
     *
     * @param orderAmount the value for eload_order_info.order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.multi_order_amount
     *
     * @return the value of eload_order_info.multi_order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getMultiOrderAmount() {
        return multiOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.multi_order_amount
     *
     * @param multiOrderAmount the value for eload_order_info.multi_order_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setMultiOrderAmount(BigDecimal multiOrderAmount) {
        this.multiOrderAmount = multiOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_currency
     *
     * @return the value of eload_order_info.order_currency
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getOrderCurrency() {
        return orderCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_currency
     *
     * @param orderCurrency the value for eload_order_info.order_currency
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency == null ? null : orderCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_rate
     *
     * @return the value of eload_order_info.order_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getOrderRate() {
        return orderRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_rate
     *
     * @param orderRate the value for eload_order_info.order_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderRate(BigDecimal orderRate) {
        this.orderRate = orderRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.realpay
     *
     * @return the value of eload_order_info.realpay
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getRealpay() {
        return realpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.realpay
     *
     * @param realpay the value for eload_order_info.realpay
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setRealpay(BigDecimal realpay) {
        this.realpay = realpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.referer
     *
     * @return the value of eload_order_info.referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.referer
     *
     * @param referer the value for eload_order_info.referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.add_time
     *
     * @return the value of eload_order_info.add_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.add_time
     *
     * @param addTime the value for eload_order_info.add_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_time
     *
     * @return the value of eload_order_info.pay_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_time
     *
     * @param payTime the value for eload_order_info.pay_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.shipping_time
     *
     * @return the value of eload_order_info.shipping_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.shipping_time
     *
     * @param shippingTime the value for eload_order_info.shipping_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingTime(Integer shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.cancel_time
     *
     * @return the value of eload_order_info.cancel_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.cancel_time
     *
     * @param cancelTime the value for eload_order_info.cancel_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCancelTime(Integer cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_note
     *
     * @return the value of eload_order_info.pay_note
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPayNote() {
        return payNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_note
     *
     * @param payNote the value for eload_order_info.pay_note
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayNote(String payNote) {
        this.payNote = payNote == null ? null : payNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.tax
     *
     * @return the value of eload_order_info.tax
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.tax
     *
     * @param tax the value for eload_order_info.tax
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.Invoice
     *
     * @return the value of eload_order_info.Invoice
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.Invoice
     *
     * @param invoice the value for eload_order_info.Invoice
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setInvoice(Boolean invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.promotion_code_youhuilv
     *
     * @return the value of eload_order_info.promotion_code_youhuilv
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPromotionCodeYouhuilv() {
        return promotionCodeYouhuilv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.promotion_code_youhuilv
     *
     * @param promotionCodeYouhuilv the value for eload_order_info.promotion_code_youhuilv
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPromotionCodeYouhuilv(String promotionCodeYouhuilv) {
        this.promotionCodeYouhuilv = promotionCodeYouhuilv == null ? null : promotionCodeYouhuilv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.promotion_code
     *
     * @return the value of eload_order_info.promotion_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPromotionCode() {
        return promotionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.promotion_code
     *
     * @param promotionCode the value for eload_order_info.promotion_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPromotionCode(String promotionCode) {
        this.promotionCode = promotionCode == null ? null : promotionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.Need_Traking_number
     *
     * @return the value of eload_order_info.Need_Traking_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getNeedTrakingNumber() {
        return needTrakingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.Need_Traking_number
     *
     * @param needTrakingNumber the value for eload_order_info.Need_Traking_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setNeedTrakingNumber(BigDecimal needTrakingNumber) {
        this.needTrakingNumber = needTrakingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.wj_linkid
     *
     * @return the value of eload_order_info.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getWjLinkid() {
        return wjLinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.wj_linkid
     *
     * @param wjLinkid the value for eload_order_info.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setWjLinkid(Integer wjLinkid) {
        this.wjLinkid = wjLinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_dao
     *
     * @return the value of eload_order_info.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getIsDao() {
        return isDao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_dao
     *
     * @param isDao the value for eload_order_info.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsDao(Integer isDao) {
        this.isDao = isDao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_ping
     *
     * @return the value of eload_order_info.is_ping
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getIsPing() {
        return isPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_ping
     *
     * @param isPing the value for eload_order_info.is_ping
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsPing(Integer isPing) {
        this.isPing = isPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.used_point
     *
     * @return the value of eload_order_info.used_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Float getUsedPoint() {
        return usedPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.used_point
     *
     * @param usedPoint the value for eload_order_info.used_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUsedPoint(Float usedPoint) {
        this.usedPoint = usedPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.point_money
     *
     * @return the value of eload_order_info.point_money
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Float getPointMoney() {
        return pointMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.point_money
     *
     * @param pointMoney the value for eload_order_info.point_money
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPointMoney(Float pointMoney) {
        this.pointMoney = pointMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_login
     *
     * @return the value of eload_order_info.is_login
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_login
     *
     * @param isLogin the value for eload_order_info.is_login
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsLogin(Byte isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_to_erp
     *
     * @return the value of eload_order_info.is_to_erp
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getIsToErp() {
        return isToErp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_to_erp
     *
     * @param isToErp the value for eload_order_info.is_to_erp
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsToErp(Boolean isToErp) {
        this.isToErp = isToErp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.wj_referer
     *
     * @return the value of eload_order_info.wj_referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getWjReferer() {
        return wjReferer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.wj_referer
     *
     * @param wjReferer the value for eload_order_info.wj_referer
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setWjReferer(String wjReferer) {
        this.wjReferer = wjReferer == null ? null : wjReferer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_method
     *
     * @return the value of eload_order_info.order_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getOrderMethod() {
        return orderMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_method
     *
     * @param orderMethod the value for eload_order_info.order_method
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderMethod(Boolean orderMethod) {
        this.orderMethod = orderMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_display_track_goods
     *
     * @return the value of eload_order_info.is_display_track_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getIsDisplayTrackGoods() {
        return isDisplayTrackGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_display_track_goods
     *
     * @param isDisplayTrackGoods the value for eload_order_info.is_display_track_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsDisplayTrackGoods(Boolean isDisplayTrackGoods) {
        this.isDisplayTrackGoods = isDisplayTrackGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.com_is_fa
     *
     * @return the value of eload_order_info.com_is_fa
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getComIsFa() {
        return comIsFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.com_is_fa
     *
     * @param comIsFa the value for eload_order_info.com_is_fa
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setComIsFa(Boolean comIsFa) {
        this.comIsFa = comIsFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.com_fa_date
     *
     * @return the value of eload_order_info.com_fa_date
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getComFaDate() {
        return comFaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.com_fa_date
     *
     * @param comFaDate the value for eload_order_info.com_fa_date
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setComFaDate(Integer comFaDate) {
        this.comFaDate = comFaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.full_reduce_discount
     *
     * @return the value of eload_order_info.full_reduce_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getFullReduceDiscount() {
        return fullReduceDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.full_reduce_discount
     *
     * @param fullReduceDiscount the value for eload_order_info.full_reduce_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setFullReduceDiscount(BigDecimal fullReduceDiscount) {
        this.fullReduceDiscount = fullReduceDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.buytype
     *
     * @return the value of eload_order_info.buytype
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getBuytype() {
        return buytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.buytype
     *
     * @param buytype the value for eload_order_info.buytype
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setBuytype(Boolean buytype) {
        this.buytype = buytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.lang
     *
     * @return the value of eload_order_info.lang
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.lang
     *
     * @param lang the value for eload_order_info.lang
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_ip
     *
     * @return the value of eload_order_info.pay_ip
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPayIp() {
        return payIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_ip
     *
     * @param payIp the value for eload_order_info.pay_ip
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayIp(String payIp) {
        this.payIp = payIp == null ? null : payIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_to_oms
     *
     * @return the value of eload_order_info.is_to_oms
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getIsToOms() {
        return isToOms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_to_oms
     *
     * @param isToOms the value for eload_order_info.is_to_oms
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsToOms(Boolean isToOms) {
        this.isToOms = isToOms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.update_time
     *
     * @return the value of eload_order_info.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.update_time
     *
     * @param updateTime the value for eload_order_info.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.used_wallet
     *
     * @return the value of eload_order_info.used_wallet
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getUsedWallet() {
        return usedWallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.used_wallet
     *
     * @param usedWallet the value for eload_order_info.used_wallet
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUsedWallet(BigDecimal usedWallet) {
        this.usedWallet = usedWallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_order_review
     *
     * @return the value of eload_order_info.is_order_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getIsOrderReview() {
        return isOrderReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_order_review
     *
     * @param isOrderReview the value for eload_order_info.is_order_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsOrderReview(Boolean isOrderReview) {
        this.isOrderReview = isOrderReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.is_point
     *
     * @return the value of eload_order_info.is_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getIsPoint() {
        return isPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.is_point
     *
     * @param isPoint the value for eload_order_info.is_point
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsPoint(Byte isPoint) {
        this.isPoint = isPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.tax_id
     *
     * @return the value of eload_order_info.tax_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.tax_id
     *
     * @param taxId the value for eload_order_info.tax_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setTaxId(String taxId) {
        this.taxId = taxId == null ? null : taxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.recieved_time
     *
     * @return the value of eload_order_info.recieved_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getRecievedTime() {
        return recievedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.recieved_time
     *
     * @param recievedTime the value for eload_order_info.recieved_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setRecievedTime(Integer recievedTime) {
        this.recievedTime = recievedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.media_source
     *
     * @return the value of eload_order_info.media_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getMediaSource() {
        return mediaSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.media_source
     *
     * @param mediaSource the value for eload_order_info.media_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setMediaSource(String mediaSource) {
        this.mediaSource = mediaSource == null ? null : mediaSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.campagin
     *
     * @return the value of eload_order_info.campagin
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getCampagin() {
        return campagin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.campagin
     *
     * @param campagin the value for eload_order_info.campagin
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCampagin(String campagin) {
        this.campagin = campagin == null ? null : campagin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.oms_release_storage
     *
     * @return the value of eload_order_info.oms_release_storage
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getOmsReleaseStorage() {
        return omsReleaseStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.oms_release_storage
     *
     * @param omsReleaseStorage the value for eload_order_info.oms_release_storage
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOmsReleaseStorage(Boolean omsReleaseStorage) {
        this.omsReleaseStorage = omsReleaseStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.cod_discount
     *
     * @return the value of eload_order_info.cod_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getCodDiscount() {
        return codDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.cod_discount
     *
     * @param codDiscount the value for eload_order_info.cod_discount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCodDiscount(BigDecimal codDiscount) {
        this.codDiscount = codDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.cod_orientation
     *
     * @return the value of eload_order_info.cod_orientation
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getCodOrientation() {
        return codOrientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.cod_orientation
     *
     * @param codOrientation the value for eload_order_info.cod_orientation
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCodOrientation(Boolean codOrientation) {
        this.codOrientation = codOrientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.order_class
     *
     * @return the value of eload_order_info.order_class
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getOrderClass() {
        return orderClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.order_class
     *
     * @param orderClass the value for eload_order_info.order_class
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderClass(Boolean orderClass) {
        this.orderClass = orderClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.retargeting
     *
     * @return the value of eload_order_info.retargeting
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getRetargeting() {
        return retargeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.retargeting
     *
     * @param retargeting the value for eload_order_info.retargeting
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setRetargeting(String retargeting) {
        this.retargeting = retargeting == null ? null : retargeting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pid
     *
     * @return the value of eload_order_info.pid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pid
     *
     * @param pid the value for eload_order_info.pid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.campaign
     *
     * @return the value of eload_order_info.campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getCampaign() {
        return campaign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.campaign
     *
     * @param campaign the value for eload_order_info.campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setCampaign(String campaign) {
        this.campaign = campaign == null ? null : campaign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.version
     *
     * @return the value of eload_order_info.version
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.version
     *
     * @param version the value for eload_order_info.version
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.date_wj_linkid_created
     *
     * @return the value of eload_order_info.date_wj_linkid_created
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getDateWjLinkidCreated() {
        return dateWjLinkidCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.date_wj_linkid_created
     *
     * @param dateWjLinkidCreated the value for eload_order_info.date_wj_linkid_created
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setDateWjLinkidCreated(Integer dateWjLinkidCreated) {
        this.dateWjLinkidCreated = dateWjLinkidCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.postback_id
     *
     * @return the value of eload_order_info.postback_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPostbackId() {
        return postbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.postback_id
     *
     * @param postbackId the value for eload_order_info.postback_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPostbackId(String postbackId) {
        this.postbackId = postbackId == null ? null : postbackId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pic_url
     *
     * @return the value of eload_order_info.pic_url
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pic_url
     *
     * @param picUrl the value for eload_order_info.pic_url
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.user_wish_refund
     *
     * @return the value of eload_order_info.user_wish_refund
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getUserWishRefund() {
        return userWishRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.user_wish_refund
     *
     * @param userWishRefund the value for eload_order_info.user_wish_refund
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUserWishRefund(Boolean userWishRefund) {
        this.userWishRefund = userWishRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.pay_platform
     *
     * @return the value of eload_order_info.pay_platform
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.pay_platform
     *
     * @param payPlatform the value for eload_order_info.pay_platform
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPayPlatform(Boolean payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.add_to_cart
     *
     * @return the value of eload_order_info.add_to_cart
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getAddToCart() {
        return addToCart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.add_to_cart
     *
     * @param addToCart the value for eload_order_info.add_to_cart
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAddToCart(Boolean addToCart) {
        this.addToCart = addToCart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.aff_source
     *
     * @return the value of eload_order_info.aff_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getAffSource() {
        return affSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.aff_source
     *
     * @param affSource the value for eload_order_info.aff_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAffSource(String affSource) {
        this.affSource = affSource == null ? null : affSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.utm_campaign
     *
     * @return the value of eload_order_info.utm_campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getUtmCampaign() {
        return utmCampaign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.utm_campaign
     *
     * @param utmCampaign the value for eload_order_info.utm_campaign
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUtmCampaign(String utmCampaign) {
        this.utmCampaign = utmCampaign == null ? null : utmCampaign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.utm_medium
     *
     * @return the value of eload_order_info.utm_medium
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getUtmMedium() {
        return utmMedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.utm_medium
     *
     * @param utmMedium the value for eload_order_info.utm_medium
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUtmMedium(String utmMedium) {
        this.utmMedium = utmMedium == null ? null : utmMedium.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_info.buy_from
     *
     * @return the value of eload_order_info.buy_from
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getBuyFrom() {
        return buyFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_info.buy_from
     *
     * @param buyFrom the value for eload_order_info.buy_from
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setBuyFrom(Boolean buyFrom) {
        this.buyFrom = buyFrom;
    }
}