package com.globalegrow.model.zaful;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public OrderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecIdIsNull() {
            addCriterion("rec_id is null");
            return (Criteria) this;
        }

        public Criteria andRecIdIsNotNull() {
            addCriterion("rec_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecIdEqualTo(Integer value) {
            addCriterion("rec_id =", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdNotEqualTo(Integer value) {
            addCriterion("rec_id <>", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdGreaterThan(Integer value) {
            addCriterion("rec_id >", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rec_id >=", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdLessThan(Integer value) {
            addCriterion("rec_id <", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdLessThanOrEqualTo(Integer value) {
            addCriterion("rec_id <=", value, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdIn(List<Integer> values) {
            addCriterion("rec_id in", values, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdNotIn(List<Integer> values) {
            addCriterion("rec_id not in", values, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdBetween(Integer value1, Integer value2) {
            addCriterion("rec_id between", value1, value2, "recId");
            return (Criteria) this;
        }

        public Criteria andRecIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rec_id not between", value1, value2, "recId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdIsNull() {
            addCriterion("child_order_id is null");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdIsNotNull() {
            addCriterion("child_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdEqualTo(Integer value) {
            addCriterion("child_order_id =", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdNotEqualTo(Integer value) {
            addCriterion("child_order_id <>", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdGreaterThan(Integer value) {
            addCriterion("child_order_id >", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("child_order_id >=", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdLessThan(Integer value) {
            addCriterion("child_order_id <", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("child_order_id <=", value, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdIn(List<Integer> values) {
            addCriterion("child_order_id in", values, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdNotIn(List<Integer> values) {
            addCriterion("child_order_id not in", values, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("child_order_id between", value1, value2, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andChildOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("child_order_id not between", value1, value2, "childOrderId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNull() {
            addCriterion("goods_sn is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNotNull() {
            addCriterion("goods_sn is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnEqualTo(String value) {
            addCriterion("goods_sn =", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotEqualTo(String value) {
            addCriterion("goods_sn <>", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThan(String value) {
            addCriterion("goods_sn >", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThanOrEqualTo(String value) {
            addCriterion("goods_sn >=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThan(String value) {
            addCriterion("goods_sn <", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThanOrEqualTo(String value) {
            addCriterion("goods_sn <=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLike(String value) {
            addCriterion("goods_sn like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotLike(String value) {
            addCriterion("goods_sn not like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIn(List<String> values) {
            addCriterion("goods_sn in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotIn(List<String> values) {
            addCriterion("goods_sn not in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnBetween(String value1, String value2) {
            addCriterion("goods_sn between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotBetween(String value1, String value2) {
            addCriterion("goods_sn not between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberIsNull() {
            addCriterion("goods_number is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberIsNotNull() {
            addCriterion("goods_number is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberEqualTo(Short value) {
            addCriterion("goods_number =", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberNotEqualTo(Short value) {
            addCriterion("goods_number <>", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberGreaterThan(Short value) {
            addCriterion("goods_number >", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberGreaterThanOrEqualTo(Short value) {
            addCriterion("goods_number >=", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberLessThan(Short value) {
            addCriterion("goods_number <", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberLessThanOrEqualTo(Short value) {
            addCriterion("goods_number <=", value, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberIn(List<Short> values) {
            addCriterion("goods_number in", values, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberNotIn(List<Short> values) {
            addCriterion("goods_number not in", values, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberBetween(Short value1, Short value2) {
            addCriterion("goods_number between", value1, value2, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsNumberNotBetween(Short value1, Short value2) {
            addCriterion("goods_number not between", value1, value2, "goodsNumber");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNull() {
            addCriterion("market_price is null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNotNull() {
            addCriterion("market_price is not null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceEqualTo(BigDecimal value) {
            addCriterion("market_price =", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotEqualTo(BigDecimal value) {
            addCriterion("market_price <>", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThan(BigDecimal value) {
            addCriterion("market_price >", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price >=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThan(BigDecimal value) {
            addCriterion("market_price <", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price <=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIn(List<BigDecimal> values) {
            addCriterion("market_price in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotIn(List<BigDecimal> values) {
            addCriterion("market_price not in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price between", value1, value2, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price not between", value1, value2, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(BigDecimal value) {
            addCriterion("goods_price =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(BigDecimal value) {
            addCriterion("goods_price <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(BigDecimal value) {
            addCriterion("goods_price >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(BigDecimal value) {
            addCriterion("goods_price <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<BigDecimal> values) {
            addCriterion("goods_price in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<BigDecimal> values) {
            addCriterion("goods_price not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountIsNull() {
            addCriterion("goods_pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountIsNotNull() {
            addCriterion("goods_pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountEqualTo(BigDecimal value) {
            addCriterion("goods_pay_amount =", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("goods_pay_amount <>", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountGreaterThan(BigDecimal value) {
            addCriterion("goods_pay_amount >", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_pay_amount >=", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountLessThan(BigDecimal value) {
            addCriterion("goods_pay_amount <", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_pay_amount <=", value, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountIn(List<BigDecimal> values) {
            addCriterion("goods_pay_amount in", values, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("goods_pay_amount not in", values, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_pay_amount between", value1, value2, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_pay_amount not between", value1, value2, "goodsPayAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceIsNull() {
            addCriterion("goods_pay_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceIsNotNull() {
            addCriterion("goods_pay_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceEqualTo(BigDecimal value) {
            addCriterion("goods_pay_price =", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceNotEqualTo(BigDecimal value) {
            addCriterion("goods_pay_price <>", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceGreaterThan(BigDecimal value) {
            addCriterion("goods_pay_price >", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_pay_price >=", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceLessThan(BigDecimal value) {
            addCriterion("goods_pay_price <", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_pay_price <=", value, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceIn(List<BigDecimal> values) {
            addCriterion("goods_pay_price in", values, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceNotIn(List<BigDecimal> values) {
            addCriterion("goods_pay_price not in", values, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_pay_price between", value1, value2, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPayPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_pay_price not between", value1, value2, "goodsPayPrice");
            return (Criteria) this;
        }

        public Criteria andSendNumberIsNull() {
            addCriterion("send_number is null");
            return (Criteria) this;
        }

        public Criteria andSendNumberIsNotNull() {
            addCriterion("send_number is not null");
            return (Criteria) this;
        }

        public Criteria andSendNumberEqualTo(Short value) {
            addCriterion("send_number =", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberNotEqualTo(Short value) {
            addCriterion("send_number <>", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberGreaterThan(Short value) {
            addCriterion("send_number >", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberGreaterThanOrEqualTo(Short value) {
            addCriterion("send_number >=", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberLessThan(Short value) {
            addCriterion("send_number <", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberLessThanOrEqualTo(Short value) {
            addCriterion("send_number <=", value, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberIn(List<Short> values) {
            addCriterion("send_number in", values, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberNotIn(List<Short> values) {
            addCriterion("send_number not in", values, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberBetween(Short value1, Short value2) {
            addCriterion("send_number between", value1, value2, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andSendNumberNotBetween(Short value1, Short value2) {
            addCriterion("send_number not between", value1, value2, "sendNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsOffIsNull() {
            addCriterion("goods_off is null");
            return (Criteria) this;
        }

        public Criteria andGoodsOffIsNotNull() {
            addCriterion("goods_off is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsOffEqualTo(Integer value) {
            addCriterion("goods_off =", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffNotEqualTo(Integer value) {
            addCriterion("goods_off <>", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffGreaterThan(Integer value) {
            addCriterion("goods_off >", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_off >=", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffLessThan(Integer value) {
            addCriterion("goods_off <", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffLessThanOrEqualTo(Integer value) {
            addCriterion("goods_off <=", value, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffIn(List<Integer> values) {
            addCriterion("goods_off in", values, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffNotIn(List<Integer> values) {
            addCriterion("goods_off not in", values, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffBetween(Integer value1, Integer value2) {
            addCriterion("goods_off between", value1, value2, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andGoodsOffNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_off not between", value1, value2, "goodsOff");
            return (Criteria) this;
        }

        public Criteria andLmtNumIsNull() {
            addCriterion("lmt_num is null");
            return (Criteria) this;
        }

        public Criteria andLmtNumIsNotNull() {
            addCriterion("lmt_num is not null");
            return (Criteria) this;
        }

        public Criteria andLmtNumEqualTo(Boolean value) {
            addCriterion("lmt_num =", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumNotEqualTo(Boolean value) {
            addCriterion("lmt_num <>", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumGreaterThan(Boolean value) {
            addCriterion("lmt_num >", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lmt_num >=", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumLessThan(Boolean value) {
            addCriterion("lmt_num <", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumLessThanOrEqualTo(Boolean value) {
            addCriterion("lmt_num <=", value, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumIn(List<Boolean> values) {
            addCriterion("lmt_num in", values, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumNotIn(List<Boolean> values) {
            addCriterion("lmt_num not in", values, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumBetween(Boolean value1, Boolean value2) {
            addCriterion("lmt_num between", value1, value2, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andLmtNumNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lmt_num not between", value1, value2, "lmtNum");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Integer value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Integer value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Integer value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Integer value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Integer value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Integer> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Integer> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Integer value1, Integer value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnIsNull() {
            addCriterion("attr_goods_sn is null");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnIsNotNull() {
            addCriterion("attr_goods_sn is not null");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnEqualTo(String value) {
            addCriterion("attr_goods_sn =", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnNotEqualTo(String value) {
            addCriterion("attr_goods_sn <>", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnGreaterThan(String value) {
            addCriterion("attr_goods_sn >", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnGreaterThanOrEqualTo(String value) {
            addCriterion("attr_goods_sn >=", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnLessThan(String value) {
            addCriterion("attr_goods_sn <", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnLessThanOrEqualTo(String value) {
            addCriterion("attr_goods_sn <=", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnLike(String value) {
            addCriterion("attr_goods_sn like", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnNotLike(String value) {
            addCriterion("attr_goods_sn not like", value, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnIn(List<String> values) {
            addCriterion("attr_goods_sn in", values, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnNotIn(List<String> values) {
            addCriterion("attr_goods_sn not in", values, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnBetween(String value1, String value2) {
            addCriterion("attr_goods_sn between", value1, value2, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andAttrGoodsSnNotBetween(String value1, String value2) {
            addCriterion("attr_goods_sn not between", value1, value2, "attrGoodsSn");
            return (Criteria) this;
        }

        public Criteria andIsDaoIsNull() {
            addCriterion("is_dao is null");
            return (Criteria) this;
        }

        public Criteria andIsDaoIsNotNull() {
            addCriterion("is_dao is not null");
            return (Criteria) this;
        }

        public Criteria andIsDaoEqualTo(Integer value) {
            addCriterion("is_dao =", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoNotEqualTo(Integer value) {
            addCriterion("is_dao <>", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoGreaterThan(Integer value) {
            addCriterion("is_dao >", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_dao >=", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoLessThan(Integer value) {
            addCriterion("is_dao <", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoLessThanOrEqualTo(Integer value) {
            addCriterion("is_dao <=", value, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoIn(List<Integer> values) {
            addCriterion("is_dao in", values, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoNotIn(List<Integer> values) {
            addCriterion("is_dao not in", values, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoBetween(Integer value1, Integer value2) {
            addCriterion("is_dao between", value1, value2, "isDao");
            return (Criteria) this;
        }

        public Criteria andIsDaoNotBetween(Integer value1, Integer value2) {
            addCriterion("is_dao not between", value1, value2, "isDao");
            return (Criteria) this;
        }

        public Criteria andPointRateIsNull() {
            addCriterion("point_rate is null");
            return (Criteria) this;
        }

        public Criteria andPointRateIsNotNull() {
            addCriterion("point_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPointRateEqualTo(Integer value) {
            addCriterion("point_rate =", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateNotEqualTo(Integer value) {
            addCriterion("point_rate <>", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateGreaterThan(Integer value) {
            addCriterion("point_rate >", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("point_rate >=", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateLessThan(Integer value) {
            addCriterion("point_rate <", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateLessThanOrEqualTo(Integer value) {
            addCriterion("point_rate <=", value, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateIn(List<Integer> values) {
            addCriterion("point_rate in", values, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateNotIn(List<Integer> values) {
            addCriterion("point_rate not in", values, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateBetween(Integer value1, Integer value2) {
            addCriterion("point_rate between", value1, value2, "pointRate");
            return (Criteria) this;
        }

        public Criteria andPointRateNotBetween(Integer value1, Integer value2) {
            addCriterion("point_rate not between", value1, value2, "pointRate");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNull() {
            addCriterion("goods_type is null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNotNull() {
            addCriterion("goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeEqualTo(Boolean value) {
            addCriterion("goods_type =", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotEqualTo(Boolean value) {
            addCriterion("goods_type <>", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThan(Boolean value) {
            addCriterion("goods_type >", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("goods_type >=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThan(Boolean value) {
            addCriterion("goods_type <", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("goods_type <=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIn(List<Boolean> values) {
            addCriterion("goods_type in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotIn(List<Boolean> values) {
            addCriterion("goods_type not in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("goods_type between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("goods_type not between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeIsNull() {
            addCriterion("free_shipping_fee is null");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeIsNotNull() {
            addCriterion("free_shipping_fee is not null");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeEqualTo(BigDecimal value) {
            addCriterion("free_shipping_fee =", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeNotEqualTo(BigDecimal value) {
            addCriterion("free_shipping_fee <>", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeGreaterThan(BigDecimal value) {
            addCriterion("free_shipping_fee >", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("free_shipping_fee >=", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeLessThan(BigDecimal value) {
            addCriterion("free_shipping_fee <", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("free_shipping_fee <=", value, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeIn(List<BigDecimal> values) {
            addCriterion("free_shipping_fee in", values, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeNotIn(List<BigDecimal> values) {
            addCriterion("free_shipping_fee not in", values, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("free_shipping_fee between", value1, value2, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andFreeShippingFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("free_shipping_fee not between", value1, value2, "freeShippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNull() {
            addCriterion("shipping_fee is null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNotNull() {
            addCriterion("shipping_fee is not null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeEqualTo(BigDecimal value) {
            addCriterion("shipping_fee =", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotEqualTo(BigDecimal value) {
            addCriterion("shipping_fee <>", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThan(BigDecimal value) {
            addCriterion("shipping_fee >", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shipping_fee >=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThan(BigDecimal value) {
            addCriterion("shipping_fee <", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shipping_fee <=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIn(List<BigDecimal> values) {
            addCriterion("shipping_fee in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotIn(List<BigDecimal> values) {
            addCriterion("shipping_fee not in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipping_fee between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipping_fee not between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andWjLinkidIsNull() {
            addCriterion("wj_linkid is null");
            return (Criteria) this;
        }

        public Criteria andWjLinkidIsNotNull() {
            addCriterion("wj_linkid is not null");
            return (Criteria) this;
        }

        public Criteria andWjLinkidEqualTo(Integer value) {
            addCriterion("wj_linkid =", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidNotEqualTo(Integer value) {
            addCriterion("wj_linkid <>", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidGreaterThan(Integer value) {
            addCriterion("wj_linkid >", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wj_linkid >=", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidLessThan(Integer value) {
            addCriterion("wj_linkid <", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidLessThanOrEqualTo(Integer value) {
            addCriterion("wj_linkid <=", value, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidIn(List<Integer> values) {
            addCriterion("wj_linkid in", values, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidNotIn(List<Integer> values) {
            addCriterion("wj_linkid not in", values, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidBetween(Integer value1, Integer value2) {
            addCriterion("wj_linkid between", value1, value2, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidNotBetween(Integer value1, Integer value2) {
            addCriterion("wj_linkid not between", value1, value2, "wjLinkid");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceIsNull() {
            addCriterion("wj_linkid_source is null");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceIsNotNull() {
            addCriterion("wj_linkid_source is not null");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceEqualTo(Boolean value) {
            addCriterion("wj_linkid_source =", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceNotEqualTo(Boolean value) {
            addCriterion("wj_linkid_source <>", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceGreaterThan(Boolean value) {
            addCriterion("wj_linkid_source >", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("wj_linkid_source >=", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceLessThan(Boolean value) {
            addCriterion("wj_linkid_source <", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceLessThanOrEqualTo(Boolean value) {
            addCriterion("wj_linkid_source <=", value, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceIn(List<Boolean> values) {
            addCriterion("wj_linkid_source in", values, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceNotIn(List<Boolean> values) {
            addCriterion("wj_linkid_source not in", values, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceBetween(Boolean value1, Boolean value2) {
            addCriterion("wj_linkid_source between", value1, value2, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andWjLinkidSourceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("wj_linkid_source not between", value1, value2, "wjLinkidSource");
            return (Criteria) this;
        }

        public Criteria andIsReviewIsNull() {
            addCriterion("is_review is null");
            return (Criteria) this;
        }

        public Criteria andIsReviewIsNotNull() {
            addCriterion("is_review is not null");
            return (Criteria) this;
        }

        public Criteria andIsReviewEqualTo(Byte value) {
            addCriterion("is_review =", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewNotEqualTo(Byte value) {
            addCriterion("is_review <>", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewGreaterThan(Byte value) {
            addCriterion("is_review >", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_review >=", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewLessThan(Byte value) {
            addCriterion("is_review <", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewLessThanOrEqualTo(Byte value) {
            addCriterion("is_review <=", value, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewIn(List<Byte> values) {
            addCriterion("is_review in", values, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewNotIn(List<Byte> values) {
            addCriterion("is_review not in", values, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewBetween(Byte value1, Byte value2) {
            addCriterion("is_review between", value1, value2, "isReview");
            return (Criteria) this;
        }

        public Criteria andIsReviewNotBetween(Byte value1, Byte value2) {
            addCriterion("is_review not between", value1, value2, "isReview");
            return (Criteria) this;
        }

        public Criteria andZafulSourceIsNull() {
            addCriterion("zaful_source is null");
            return (Criteria) this;
        }

        public Criteria andZafulSourceIsNotNull() {
            addCriterion("zaful_source is not null");
            return (Criteria) this;
        }

        public Criteria andZafulSourceEqualTo(String value) {
            addCriterion("zaful_source =", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceNotEqualTo(String value) {
            addCriterion("zaful_source <>", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceGreaterThan(String value) {
            addCriterion("zaful_source >", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceGreaterThanOrEqualTo(String value) {
            addCriterion("zaful_source >=", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceLessThan(String value) {
            addCriterion("zaful_source <", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceLessThanOrEqualTo(String value) {
            addCriterion("zaful_source <=", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceLike(String value) {
            addCriterion("zaful_source like", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceNotLike(String value) {
            addCriterion("zaful_source not like", value, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceIn(List<String> values) {
            addCriterion("zaful_source in", values, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceNotIn(List<String> values) {
            addCriterion("zaful_source not in", values, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceBetween(String value1, String value2) {
            addCriterion("zaful_source between", value1, value2, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andZafulSourceNotBetween(String value1, String value2) {
            addCriterion("zaful_source not between", value1, value2, "zafulSource");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIsNull() {
            addCriterion("delivery_level is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIsNotNull() {
            addCriterion("delivery_level is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelEqualTo(Byte value) {
            addCriterion("delivery_level =", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotEqualTo(Byte value) {
            addCriterion("delivery_level <>", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelGreaterThan(Byte value) {
            addCriterion("delivery_level >", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("delivery_level >=", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelLessThan(Byte value) {
            addCriterion("delivery_level <", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelLessThanOrEqualTo(Byte value) {
            addCriterion("delivery_level <=", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIn(List<Byte> values) {
            addCriterion("delivery_level in", values, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotIn(List<Byte> values) {
            addCriterion("delivery_level not in", values, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelBetween(Byte value1, Byte value2) {
            addCriterion("delivery_level between", value1, value2, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("delivery_level not between", value1, value2, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponIsNull() {
            addCriterion("isUsedDealsCoupon is null");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponIsNotNull() {
            addCriterion("isUsedDealsCoupon is not null");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponEqualTo(Boolean value) {
            addCriterion("isUsedDealsCoupon =", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponNotEqualTo(Boolean value) {
            addCriterion("isUsedDealsCoupon <>", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponGreaterThan(Boolean value) {
            addCriterion("isUsedDealsCoupon >", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isUsedDealsCoupon >=", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponLessThan(Boolean value) {
            addCriterion("isUsedDealsCoupon <", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponLessThanOrEqualTo(Boolean value) {
            addCriterion("isUsedDealsCoupon <=", value, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponIn(List<Boolean> values) {
            addCriterion("isUsedDealsCoupon in", values, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponNotIn(List<Boolean> values) {
            addCriterion("isUsedDealsCoupon not in", values, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponBetween(Boolean value1, Boolean value2) {
            addCriterion("isUsedDealsCoupon between", value1, value2, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andIsuseddealscouponNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isUsedDealsCoupon not between", value1, value2, "isuseddealscoupon");
            return (Criteria) this;
        }

        public Criteria andGradeCodeIsNull() {
            addCriterion("grade_code is null");
            return (Criteria) this;
        }

        public Criteria andGradeCodeIsNotNull() {
            addCriterion("grade_code is not null");
            return (Criteria) this;
        }

        public Criteria andGradeCodeEqualTo(Byte value) {
            addCriterion("grade_code =", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeNotEqualTo(Byte value) {
            addCriterion("grade_code <>", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeGreaterThan(Byte value) {
            addCriterion("grade_code >", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("grade_code >=", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeLessThan(Byte value) {
            addCriterion("grade_code <", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeLessThanOrEqualTo(Byte value) {
            addCriterion("grade_code <=", value, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeIn(List<Byte> values) {
            addCriterion("grade_code in", values, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeNotIn(List<Byte> values) {
            addCriterion("grade_code not in", values, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeBetween(Byte value1, Byte value2) {
            addCriterion("grade_code between", value1, value2, "gradeCode");
            return (Criteria) this;
        }

        public Criteria andGradeCodeNotBetween(Byte value1, Byte value2) {
            addCriterion("grade_code not between", value1, value2, "gradeCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eload_order_goods
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 13 18:13:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}