package com.globalegrow.model.zaful;

import java.math.BigDecimal;
import java.util.Date;

public class OrderGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.rec_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.child_order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer childOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Short goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.market_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_pay_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal goodsPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_pay_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal goodsPayPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.send_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Short sendNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_off
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer goodsOff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.lmt_num
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean lmtNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.addtime
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.attr_goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String attrGoodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer isDao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.point_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer pointRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.goods_type
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal freeShippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private BigDecimal shippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Integer wjLinkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.wj_linkid_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean wjLinkidSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.is_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte isReview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.zaful_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private String zafulSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.delivery_level
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte deliveryLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.isUsedDealsCoupon
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Boolean isuseddealscoupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eload_order_goods.grade_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    private Byte gradeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.rec_id
     *
     * @return the value of eload_order_goods.rec_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.rec_id
     *
     * @param recId the value for eload_order_goods.rec_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.order_id
     *
     * @return the value of eload_order_goods.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.order_id
     *
     * @param orderId the value for eload_order_goods.order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.child_order_id
     *
     * @return the value of eload_order_goods.child_order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getChildOrderId() {
        return childOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.child_order_id
     *
     * @param childOrderId the value for eload_order_goods.child_order_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setChildOrderId(Integer childOrderId) {
        this.childOrderId = childOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_id
     *
     * @return the value of eload_order_goods.goods_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_id
     *
     * @param goodsId the value for eload_order_goods.goods_id
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_name
     *
     * @return the value of eload_order_goods.goods_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_name
     *
     * @param goodsName the value for eload_order_goods.goods_name
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_sn
     *
     * @return the value of eload_order_goods.goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_sn
     *
     * @param goodsSn the value for eload_order_goods.goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_number
     *
     * @return the value of eload_order_goods.goods_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_number
     *
     * @param goodsNumber the value for eload_order_goods.goods_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.market_price
     *
     * @return the value of eload_order_goods.market_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.market_price
     *
     * @param marketPrice the value for eload_order_goods.market_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_price
     *
     * @return the value of eload_order_goods.goods_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_price
     *
     * @param goodsPrice the value for eload_order_goods.goods_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_pay_amount
     *
     * @return the value of eload_order_goods.goods_pay_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getGoodsPayAmount() {
        return goodsPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_pay_amount
     *
     * @param goodsPayAmount the value for eload_order_goods.goods_pay_amount
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsPayAmount(BigDecimal goodsPayAmount) {
        this.goodsPayAmount = goodsPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_pay_price
     *
     * @return the value of eload_order_goods.goods_pay_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getGoodsPayPrice() {
        return goodsPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_pay_price
     *
     * @param goodsPayPrice the value for eload_order_goods.goods_pay_price
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsPayPrice(BigDecimal goodsPayPrice) {
        this.goodsPayPrice = goodsPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.send_number
     *
     * @return the value of eload_order_goods.send_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Short getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.send_number
     *
     * @param sendNumber the value for eload_order_goods.send_number
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setSendNumber(Short sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_off
     *
     * @return the value of eload_order_goods.goods_off
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getGoodsOff() {
        return goodsOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_off
     *
     * @param goodsOff the value for eload_order_goods.goods_off
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsOff(Integer goodsOff) {
        this.goodsOff = goodsOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.lmt_num
     *
     * @return the value of eload_order_goods.lmt_num
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getLmtNum() {
        return lmtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.lmt_num
     *
     * @param lmtNum the value for eload_order_goods.lmt_num
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setLmtNum(Boolean lmtNum) {
        this.lmtNum = lmtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.addtime
     *
     * @return the value of eload_order_goods.addtime
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.addtime
     *
     * @param addtime the value for eload_order_goods.addtime
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.attr_goods_sn
     *
     * @return the value of eload_order_goods.attr_goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getAttrGoodsSn() {
        return attrGoodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.attr_goods_sn
     *
     * @param attrGoodsSn the value for eload_order_goods.attr_goods_sn
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setAttrGoodsSn(String attrGoodsSn) {
        this.attrGoodsSn = attrGoodsSn == null ? null : attrGoodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.is_dao
     *
     * @return the value of eload_order_goods.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getIsDao() {
        return isDao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.is_dao
     *
     * @param isDao the value for eload_order_goods.is_dao
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsDao(Integer isDao) {
        this.isDao = isDao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.point_rate
     *
     * @return the value of eload_order_goods.point_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getPointRate() {
        return pointRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.point_rate
     *
     * @param pointRate the value for eload_order_goods.point_rate
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setPointRate(Integer pointRate) {
        this.pointRate = pointRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.goods_type
     *
     * @return the value of eload_order_goods.goods_type
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.goods_type
     *
     * @param goodsType the value for eload_order_goods.goods_type
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGoodsType(Boolean goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.free_shipping_fee
     *
     * @return the value of eload_order_goods.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getFreeShippingFee() {
        return freeShippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.free_shipping_fee
     *
     * @param freeShippingFee the value for eload_order_goods.free_shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setFreeShippingFee(BigDecimal freeShippingFee) {
        this.freeShippingFee = freeShippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.shipping_fee
     *
     * @return the value of eload_order_goods.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.shipping_fee
     *
     * @param shippingFee the value for eload_order_goods.shipping_fee
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.update_time
     *
     * @return the value of eload_order_goods.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.update_time
     *
     * @param updateTime the value for eload_order_goods.update_time
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.wj_linkid
     *
     * @return the value of eload_order_goods.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Integer getWjLinkid() {
        return wjLinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.wj_linkid
     *
     * @param wjLinkid the value for eload_order_goods.wj_linkid
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setWjLinkid(Integer wjLinkid) {
        this.wjLinkid = wjLinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.wj_linkid_source
     *
     * @return the value of eload_order_goods.wj_linkid_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getWjLinkidSource() {
        return wjLinkidSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.wj_linkid_source
     *
     * @param wjLinkidSource the value for eload_order_goods.wj_linkid_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setWjLinkidSource(Boolean wjLinkidSource) {
        this.wjLinkidSource = wjLinkidSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.is_review
     *
     * @return the value of eload_order_goods.is_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getIsReview() {
        return isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.is_review
     *
     * @param isReview the value for eload_order_goods.is_review
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsReview(Byte isReview) {
        this.isReview = isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.zaful_source
     *
     * @return the value of eload_order_goods.zaful_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public String getZafulSource() {
        return zafulSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.zaful_source
     *
     * @param zafulSource the value for eload_order_goods.zaful_source
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setZafulSource(String zafulSource) {
        this.zafulSource = zafulSource == null ? null : zafulSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.delivery_level
     *
     * @return the value of eload_order_goods.delivery_level
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getDeliveryLevel() {
        return deliveryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.delivery_level
     *
     * @param deliveryLevel the value for eload_order_goods.delivery_level
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setDeliveryLevel(Byte deliveryLevel) {
        this.deliveryLevel = deliveryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.isUsedDealsCoupon
     *
     * @return the value of eload_order_goods.isUsedDealsCoupon
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Boolean getIsuseddealscoupon() {
        return isuseddealscoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.isUsedDealsCoupon
     *
     * @param isuseddealscoupon the value for eload_order_goods.isUsedDealsCoupon
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setIsuseddealscoupon(Boolean isuseddealscoupon) {
        this.isuseddealscoupon = isuseddealscoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eload_order_goods.grade_code
     *
     * @return the value of eload_order_goods.grade_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public Byte getGradeCode() {
        return gradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eload_order_goods.grade_code
     *
     * @param gradeCode the value for eload_order_goods.grade_code
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    public void setGradeCode(Byte gradeCode) {
        this.gradeCode = gradeCode;
    }
}