SELECT COUNT(DISTINCT CART_UV) CART_UV
,SUM(CART_LOGIN_CLICK) CL_CLICK
,COUNT(DISTINCT CHECK_OUT_UV) CO_UV
,COUNT(DISTINCT CART_SIGN_UP_UV) SIGN_UV
,COUNT(DISTINCT CART_LOGIN_UV) LOGIN_UV
,COUNT(DISTINCT ADDRESS_PAGE_UV) ADD_UV
,SUM(CHECK_OUT_CLICK_NUM) CO_CLICK
,COUNT(DISTINCT ORDER_CONFIRM_UV) OC_UV
,SUM(CART_SIGN_UP_CLICK) SIGN_CLICK
,DAY_START,BTS_PLAN_ID,BTS_VERSION_ID,BTS_BUCKET_ID,POLICY FROM BTS_RG_CART_REPORT GROUP BY DAY_START,BTS_PLAN_ID,BTS_VERSION_ID,BTS_BUCKET_ID,POLICY