spring:
  profiles:
    active: @profiles.active@
  application:
     name: http-kylin-decorate
logging:
#  config: classpath:logback-spring.xml
  path: logs
  file: logs/kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] %logger{50} - %msg%n'
server:
  undertow:
    io-threads: 8
    worker-threads: 64
    direct-buffers:
  compression:
    enabled: true

---
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dy_report?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 30000

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 172.31.44.72:38194
      eager: true
#172.31.44.72:38194
#52.200.84.145:38194
  redis:
    timeout: 86400
    password: 6e1KWyC29w
#    sentinel:
#      master: sentinel-172.31.42.160-6383
#      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
    #测试地址，外网ip
    cluster:
      nodes[0]: 54.156.168.17:6381
      nodes[1]: 54.156.168.17:6382
      nodes[2]: 34.235.224.156:6383
      nodes[3]: 34.235.224.156:6384
      nodes[4]: 18.211.140.191:6381
      nodes[5]: 34.235.224.156:6384
      nodes[6]: 18.211.140.191:6381

#    sentinel:
#      master: sentinel-192.168.0.31-6420
#      nodes: 192.168.0.45:26406,192.168.0.31:6421,192.168.0.32:6422
#  elasticsearch:
#    jest:
#      uris: http://18.213.71.71:9200,http://18.213.41.233:9200,http://52.204.111.230:9200
#      read-timeout: 20000
#      connection-timeout: 20000
#http://172.31.47.84:9202,http://172.31.43.158:9202,http://172.31.55.231:9202

mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38091

app:
  es:
    index-prefix: dy-app-data-temp-
    index-aliases: search-temp-logs
  redis:
    readtime:
      prefix: dy_rt_p_

---
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.202.56.79:3306/dy_report?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Hqyg@123456
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 30000
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    #测试地址，外网ip
    cluster:
      nodes[0]: 54.156.168.17:6381
      nodes[1]: 54.156.168.17:6382
      nodes[2]: 34.235.224.156:6383
      nodes[3]: 34.235.224.156:6384
      nodes[4]: 18.211.140.191:6381
      nodes[5]: 34.235.224.156:6384
      nodes[6]: 18.211.140.191:6381

  # nodes[0]: 172.31.47.78:6382
#      nodes[1]: 172.31.47.222:6380
#      nodes[2]: 172.31.47.222:6381
#      nodes[3]: 172.31.44.253:6379
#      nodes[4]: 172.31.44.253:6380
#      nodes[5]: 172.31.47.78:6383

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 172.31.44.72:38194
      eager: true
#  elasticsearch:
#    jest:
#      uris: http://172.31.51.179:9200,http://172.31.51.59:9200,http://172.31.51.250:9200
#      read-timeout: 20000
#      connection-timeout: 20000
#      username: esearch-ai-aws
#      password: a@ss&2@1aaAQ

mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38093
app:
  es:
    index-prefix: dy-app-data-temp-
    index-aliases: search-temp-logs
  redis:
    readtime:
      prefix: dy_rt_p_
---
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: logs/kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://glbg_all_prd_mysql_m.gw-internel.com:3307/dy_report?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: dy_report
    password: h6eUzIRzVP
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 30000

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 172.31.44.72:48194
      eager: true
#172.31.47.78:6382|172.31.47.222:6380|172.31.47.222:6381|172.31.44.253:6379|172.31.44.253:6380|172.31.47.78:6383
#6e1KWyC29w
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    cluster:
      nodes[0]: 172.31.47.78:6382
      nodes[1]: 172.31.47.222:6380
      nodes[2]: 172.31.47.222:6381
      nodes[3]: 172.31.44.253:6379
      nodes[4]: 172.31.44.253:6380
      nodes[5]: 172.31.47.78:6383
#    pool:
#      max-active: 64
#      max-idle: 64
#      min-idle: 8
#  elasticsearch:
#    jest:
#      uris: http://172.31.51.179:9200,http://172.31.51.59:9200,http://172.31.51.250:9200
#      read-timeout: 20000
#      connection-timeout: 20000
#      username: esearch-ai-aws
#      password: a@ss&2@1aaAQ
mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38093
app:
  es:
    index-prefix: dy-app-data-temp-
    index-aliases: search-temp-logs
    index-type: log-test
  redis:
    readtime:
      prefix: dy_rt_p_