spring:
  profiles:
    active: @profiles.active@
logging:
#  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR

---
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: debug
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.202.56.79:3306/dy_report?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Hqyg@123456
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 30000
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  cache:
    cache-names:

mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38093

---
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: info
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bts_all_prd_mysql_m.gw-internel.com:3306/dy_report?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: bts_m_user
    password: cjQ6lt2vir
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 30000
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  cache:
    cache-names:

mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38093