package com.globalegrow.mapper.zaful;

import com.globalegrow.model.zaful.OrderGoods;
import com.globalegrow.model.zaful.OrderGoodsExample;
import com.globalegrow.model.zaful.OrderGoodsWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface OrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int deleteByExample(OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int insert(OrderGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int insertSelective(OrderGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    OrderGoodsWithBLOBs selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderGoodsWithBLOBs record, @Param("example") OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") OrderGoodsWithBLOBs record, @Param("example") OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExample(@Param("record") OrderGoods record, @Param("example") OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKeySelective(OrderGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(OrderGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_goods
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKey(OrderGoods record);
}