package com.globalegrow.mapper.zaful;

import com.globalegrow.model.zaful.OrderInfo;
import com.globalegrow.model.zaful.OrderInfoExample;
import com.globalegrow.model.zaful.OrderInfoWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int deleteByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int insert(OrderInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int insertSelective(OrderInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    OrderInfoWithBLOBs selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderInfoWithBLOBs record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") OrderInfoWithBLOBs record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByExample(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKeySelective(OrderInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(OrderInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eload_order_info
     *
     * @mbg.generated Fri Jul 13 18:13:44 CST 2018
     */
    int updateByPrimaryKey(OrderInfo record);
}