package com.globalegrow.dy.model;

import java.util.Date;

public class BtsReportFieldConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.bts_plan_id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private Long btsPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.bts_product_line_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private String btsProductLineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private String reportFieldCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_name
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private String reportFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.create_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.update_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_BTS_REPORT_FIELD_CONFIG.create_by
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.id
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.id
     *
     * @param id the value for DY_BTS_REPORT_FIELD_CONFIG.id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.bts_plan_id
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.bts_plan_id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public Long getBtsPlanId() {
        return btsPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.bts_plan_id
     *
     * @param btsPlanId the value for DY_BTS_REPORT_FIELD_CONFIG.bts_plan_id
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setBtsPlanId(Long btsPlanId) {
        this.btsPlanId = btsPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.bts_product_line_code
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.bts_product_line_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public String getBtsProductLineCode() {
        return btsProductLineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.bts_product_line_code
     *
     * @param btsProductLineCode the value for DY_BTS_REPORT_FIELD_CONFIG.bts_product_line_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setBtsProductLineCode(String btsProductLineCode) {
        this.btsProductLineCode = btsProductLineCode == null ? null : btsProductLineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_code
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.report_field_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public String getReportFieldCode() {
        return reportFieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_code
     *
     * @param reportFieldCode the value for DY_BTS_REPORT_FIELD_CONFIG.report_field_code
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setReportFieldCode(String reportFieldCode) {
        this.reportFieldCode = reportFieldCode == null ? null : reportFieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_name
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.report_field_name
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public String getReportFieldName() {
        return reportFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.report_field_name
     *
     * @param reportFieldName the value for DY_BTS_REPORT_FIELD_CONFIG.report_field_name
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setReportFieldName(String reportFieldName) {
        this.reportFieldName = reportFieldName == null ? null : reportFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.create_time
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.create_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.create_time
     *
     * @param createTime the value for DY_BTS_REPORT_FIELD_CONFIG.create_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.update_time
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.update_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.update_time
     *
     * @param updateTime the value for DY_BTS_REPORT_FIELD_CONFIG.update_time
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_BTS_REPORT_FIELD_CONFIG.create_by
     *
     * @return the value of DY_BTS_REPORT_FIELD_CONFIG.create_by
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_BTS_REPORT_FIELD_CONFIG.create_by
     *
     * @param createBy the value for DY_BTS_REPORT_FIELD_CONFIG.create_by
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }
}