package com.globalegrow.dy.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BtsReportFieldConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public BtsReportFieldConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdIsNull() {
            addCriterion("bts_plan_id is null");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdIsNotNull() {
            addCriterion("bts_plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdEqualTo(Long value) {
            addCriterion("bts_plan_id =", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdNotEqualTo(Long value) {
            addCriterion("bts_plan_id <>", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdGreaterThan(Long value) {
            addCriterion("bts_plan_id >", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdGreaterThanOrEqualTo(Long value) {
            addCriterion("bts_plan_id >=", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdLessThan(Long value) {
            addCriterion("bts_plan_id <", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdLessThanOrEqualTo(Long value) {
            addCriterion("bts_plan_id <=", value, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdIn(List<Long> values) {
            addCriterion("bts_plan_id in", values, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdNotIn(List<Long> values) {
            addCriterion("bts_plan_id not in", values, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdBetween(Long value1, Long value2) {
            addCriterion("bts_plan_id between", value1, value2, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsPlanIdNotBetween(Long value1, Long value2) {
            addCriterion("bts_plan_id not between", value1, value2, "btsPlanId");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeIsNull() {
            addCriterion("bts_product_line_code is null");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeIsNotNull() {
            addCriterion("bts_product_line_code is not null");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeEqualTo(String value) {
            addCriterion("bts_product_line_code =", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeNotEqualTo(String value) {
            addCriterion("bts_product_line_code <>", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeGreaterThan(String value) {
            addCriterion("bts_product_line_code >", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bts_product_line_code >=", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeLessThan(String value) {
            addCriterion("bts_product_line_code <", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeLessThanOrEqualTo(String value) {
            addCriterion("bts_product_line_code <=", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeLike(String value) {
            addCriterion("bts_product_line_code like", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeNotLike(String value) {
            addCriterion("bts_product_line_code not like", value, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeIn(List<String> values) {
            addCriterion("bts_product_line_code in", values, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeNotIn(List<String> values) {
            addCriterion("bts_product_line_code not in", values, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeBetween(String value1, String value2) {
            addCriterion("bts_product_line_code between", value1, value2, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andBtsProductLineCodeNotBetween(String value1, String value2) {
            addCriterion("bts_product_line_code not between", value1, value2, "btsProductLineCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeIsNull() {
            addCriterion("report_field_code is null");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeIsNotNull() {
            addCriterion("report_field_code is not null");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeEqualTo(String value) {
            addCriterion("report_field_code =", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeNotEqualTo(String value) {
            addCriterion("report_field_code <>", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeGreaterThan(String value) {
            addCriterion("report_field_code >", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeGreaterThanOrEqualTo(String value) {
            addCriterion("report_field_code >=", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeLessThan(String value) {
            addCriterion("report_field_code <", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeLessThanOrEqualTo(String value) {
            addCriterion("report_field_code <=", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeLike(String value) {
            addCriterion("report_field_code like", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeNotLike(String value) {
            addCriterion("report_field_code not like", value, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeIn(List<String> values) {
            addCriterion("report_field_code in", values, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeNotIn(List<String> values) {
            addCriterion("report_field_code not in", values, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeBetween(String value1, String value2) {
            addCriterion("report_field_code between", value1, value2, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldCodeNotBetween(String value1, String value2) {
            addCriterion("report_field_code not between", value1, value2, "reportFieldCode");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameIsNull() {
            addCriterion("report_field_name is null");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameIsNotNull() {
            addCriterion("report_field_name is not null");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameEqualTo(String value) {
            addCriterion("report_field_name =", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameNotEqualTo(String value) {
            addCriterion("report_field_name <>", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameGreaterThan(String value) {
            addCriterion("report_field_name >", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("report_field_name >=", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameLessThan(String value) {
            addCriterion("report_field_name <", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameLessThanOrEqualTo(String value) {
            addCriterion("report_field_name <=", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameLike(String value) {
            addCriterion("report_field_name like", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameNotLike(String value) {
            addCriterion("report_field_name not like", value, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameIn(List<String> values) {
            addCriterion("report_field_name in", values, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameNotIn(List<String> values) {
            addCriterion("report_field_name not in", values, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameBetween(String value1, String value2) {
            addCriterion("report_field_name between", value1, value2, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andReportFieldNameNotBetween(String value1, String value2) {
            addCriterion("report_field_name not between", value1, value2, "reportFieldName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeIsNull() {
            addCriterion("bts_plan_code is null");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeIsNotNull() {
            addCriterion("bts_plan_code is not null");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeEqualTo(String value) {
            addCriterion("bts_plan_code =", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeNotEqualTo(String value) {
            addCriterion("bts_plan_code <>", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeGreaterThan(String value) {
            addCriterion("bts_plan_code >", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bts_plan_code >=", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeLessThan(String value) {
            addCriterion("bts_plan_code <", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeLessThanOrEqualTo(String value) {
            addCriterion("bts_plan_code <=", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeLike(String value) {
            addCriterion("bts_plan_code like", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeNotLike(String value) {
            addCriterion("bts_plan_code not like", value, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeIn(List<String> values) {
            addCriterion("bts_plan_code in", values, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeNotIn(List<String> values) {
            addCriterion("bts_plan_code not in", values, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeBetween(String value1, String value2) {
            addCriterion("bts_plan_code between", value1, value2, "btsPlanCode");
            return (Criteria) this;
        }

        public Criteria andBtsPlanCodeNotBetween(String value1, String value2) {
            addCriterion("bts_plan_code not between", value1, value2, "btsPlanCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 19 15:08:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Wed Sep 19 15:08:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}