package com.globalegrow.dy.model;

import java.util.Date;

public class DyReportKylinConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.report_id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private Long reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.description
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.kylin_user_name_password
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String kylinUserNamePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.kylin_query_adress
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String kylinQueryAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.create_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.update_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.create_by
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.kylin_project_name
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String kylinProjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.query_type
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String queryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.website_code
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String websiteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_report_kylin_config.kylin_query_sql
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    private String kylinQuerySql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.id
     *
     * @return the value of dy_report_kylin_config.id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.id
     *
     * @param id the value for dy_report_kylin_config.id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.report_id
     *
     * @return the value of dy_report_kylin_config.report_id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.report_id
     *
     * @param reportId the value for dy_report_kylin_config.report_id
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.description
     *
     * @return the value of dy_report_kylin_config.description
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.description
     *
     * @param description the value for dy_report_kylin_config.description
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.kylin_user_name_password
     *
     * @return the value of dy_report_kylin_config.kylin_user_name_password
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getKylinUserNamePassword() {
        return kylinUserNamePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.kylin_user_name_password
     *
     * @param kylinUserNamePassword the value for dy_report_kylin_config.kylin_user_name_password
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setKylinUserNamePassword(String kylinUserNamePassword) {
        this.kylinUserNamePassword = kylinUserNamePassword == null ? null : kylinUserNamePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.kylin_query_adress
     *
     * @return the value of dy_report_kylin_config.kylin_query_adress
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getKylinQueryAdress() {
        return kylinQueryAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.kylin_query_adress
     *
     * @param kylinQueryAdress the value for dy_report_kylin_config.kylin_query_adress
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setKylinQueryAdress(String kylinQueryAdress) {
        this.kylinQueryAdress = kylinQueryAdress == null ? null : kylinQueryAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.create_time
     *
     * @return the value of dy_report_kylin_config.create_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.create_time
     *
     * @param createTime the value for dy_report_kylin_config.create_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.update_time
     *
     * @return the value of dy_report_kylin_config.update_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.update_time
     *
     * @param updateTime the value for dy_report_kylin_config.update_time
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.create_by
     *
     * @return the value of dy_report_kylin_config.create_by
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.create_by
     *
     * @param createBy the value for dy_report_kylin_config.create_by
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.kylin_project_name
     *
     * @return the value of dy_report_kylin_config.kylin_project_name
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getKylinProjectName() {
        return kylinProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.kylin_project_name
     *
     * @param kylinProjectName the value for dy_report_kylin_config.kylin_project_name
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setKylinProjectName(String kylinProjectName) {
        this.kylinProjectName = kylinProjectName == null ? null : kylinProjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.query_type
     *
     * @return the value of dy_report_kylin_config.query_type
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getQueryType() {
        return queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.query_type
     *
     * @param queryType the value for dy_report_kylin_config.query_type
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setQueryType(String queryType) {
        this.queryType = queryType == null ? null : queryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.website_code
     *
     * @return the value of dy_report_kylin_config.website_code
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getWebsiteCode() {
        return websiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.website_code
     *
     * @param websiteCode the value for dy_report_kylin_config.website_code
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setWebsiteCode(String websiteCode) {
        this.websiteCode = websiteCode == null ? null : websiteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_report_kylin_config.kylin_query_sql
     *
     * @return the value of dy_report_kylin_config.kylin_query_sql
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public String getKylinQuerySql() {
        return kylinQuerySql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_report_kylin_config.kylin_query_sql
     *
     * @param kylinQuerySql the value for dy_report_kylin_config.kylin_query_sql
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    public void setKylinQuerySql(String kylinQuerySql) {
        this.kylinQuerySql = kylinQuerySql == null ? null : kylinQuerySql.trim();
    }
}