spring:
  profiles:
    active: dev
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: kylin-report.log
  level:
    root: error
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
server:
  undertow:
    io-threads: 128
    worker-threads: 1024
  compression:
    enabled: true
---
spring:
  profiles: dev
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: mymaster
      nodes: 172.31.59.13:26380,172.31.57.199:26380,172.31.52.145:26380
    pool:
      max-active: 64
      max-idle: 64
      min-idle: 8
  elasticsearch:
    jest:
      uris: http://172.31.51.179:9200,http://172.31.51.59:9200,http://172.31.51.250:9200
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
mybatis:
  mapperLocations: classpath*:com/globalegrow/dy/mapper/*.xml
  type-aliases-package: com.globalegrow.dy.model

server:
  port: 38093

app:
  es:
    index-prefix: dy-app-test
    index-aliases: search-logs-test
    index-type: log-test
  redis:
    readtime:
      prefix: dy_rt_p_