spring:
  profiles:
    active: prod
  application:
    name: dy-realtime-data-query-service
logging:
  #  config: classpath:logback-spring.xml
  path: logs
  file: logs/dy-realtime-data-query-service.log
  level:
    root: info
    org.springframework: ERROR
    sun.rmi: ERROR
    org.apache.http: ERROR
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%-5level] %logger{50} - %msg%n'
server:
  undertow:
    io-threads: 128
    worker-threads: 1024
  compression:
    enabled: false
---
spring:
  profiles: dev
  elasticsearch:
    jest:
      uris[0]: http://100.26.74.93:9202
      uris[1]: http://100.26.77.0:9202
      uris[2]: http://18.215.206.192:9202
      uris[3]: http://50.16.25.252:9202
      uris[4]: http://54.144.128.124:9202
      uris[5]: http://18.204.149.153:9202
      read-timeout: 5000
      connection-timeout: 5000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  cloud:
    sentinel:
      transport:
        dashboard: localhost:38194
        port: 38193
      eager: true

server:
  port: 38193

app:
  es:
    index-prefix: dy-zf-app-
    index-aliases: search-logs-test
    index-type: log
  redis:
    readtime:
      prefix: dy_rt_p_

redis:
  type: sentinel
  master: sentinel-172.31.26.237-6379
  nodes: redis://172.31.26.152:6380,redis://172.31.26.237:6380,redis://172.31.26.162:6383
  password: 6e1KWyC29w

---
spring:
  profiles: prod
  elasticsearch:
    jest:
      uris[0]: http://172.31.32.62:9202
      uris[1]: http://172.31.43.158:9202
      uris[2]: http://172.31.47.84:9202
      uris[3]: http://172.31.55.231:9202
      uris[4]: http://172.31.62.107:9202
      uris[5]: http://172.31.62.2:9202
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  cloud:
    sentinel:
      transport:
        dashboard: 172.31.44.72:38194
        #port: 38193
      eager: true
server:
  port: 38193

app:
  es:
    index-prefix: dy-zf-app-
    index-aliases: search-app-logs
    index-type: log
  redis:
    readtime:
      prefix: dy_rt_p_

redis:
  type: cluster
  nodes: redis://172.31.47.78:6382,redis://172.31.47.222:6380,redis://172.31.47.222:6381,redis://172.31.44.253:6379,redis://172.31.44.253:6380,redis://172.31.47.78:6383
  password: 6e1KWyC29w

---
spring:
  profiles: prod-event
  elasticsearch:
    jest:
      uris[0]: http://172.31.32.62:9202
      uris[1]: http://172.31.43.158:9202
      uris[2]: http://172.31.47.84:9202
      uris[3]: http://172.31.55.231:9202
      uris[4]: http://172.31.62.107:9202
      uris[5]: http://172.31.62.2:9202
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
server:
  port: 38193

app:
  es:
    index-prefix: dy-zf-app-
    index-aliases: search-app-logs
    index-type: log

---
spring:
  profiles: prod-one-thousand
  elasticsearch:
    jest:
      uris[0]: http://172.31.32.62:9202
      uris[1]: http://172.31.43.158:9202
      uris[2]: http://172.31.47.84:9202
      uris[3]: http://172.31.55.231:9202
      uris[4]: http://172.31.62.107:9202
      uris[5]: http://172.31.62.2:9202
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
server:
  port: 38193

app:
  es:
    index-prefix: dy-user-event-limit-one-thousand
    index-aliases: search-app-logs
    index-type: log

---
spring:
  profiles: kexing
  elasticsearch:
    jest:
      uris[0]: http://10.4.4.87:9202
      uris[1]: http://10.4.4.88:9202
      uris[2]: http://10.4.4.89:9202
      read-timeout: 20000
      connection-timeout: 20000
#      username: esearch-ai-aws
#      password: a@ss&2@1aaAQ
server:
  port: 38193

app:
  es:
    index-prefix: dy-zf-app-
    index-aliases: search-app-logs
    index-type: log