spring:
  profiles:
    active: @profiles.active@
logging:
  config: classpath:logback-spring.xml
  path: logs
  file: bts-gb-report.log
  level:
    root: info
    org.springframework: ERROR
---
spring:
  profiles: test
  hbase:
    zkServers: 172.31.61.192:2181,172.31.62.7:2181,172.31.59.31:2181,172.31.62.153:2181,172.31.36.227:2181,172.31.40.73:2181
  elasticsearch:
    jest:
      uris[0]: http://172.31.51.59:9200
      uris[1]: http://172.31.51.250:9200
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-dimensions_gb_recommend-test
    producer:
      client-id: bts-gb-log-test
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092


app:
  kafka:
    log-source-topic: glbg-analitic
    gb-good-detail-rec-topic: dy_bts_gb_gd_rec_report
  hbase:
    gb-cookie-userid-table: dy_gb_cookie_userid_rel
    gb-cookie-user-clumn-family: cookie_userid
  redis:
    gb-adt-expired-seconds: 1209600

server:
  port: 38087

---
spring:
  profiles: prod
  hbase:
    zkServers: bts-master:2181,bts-masterbak:2181,bts-datanode01:2181,bts-datanode02:2181,bts-datanode03:2181,bts-datanode04:2181
  elasticsearch:
    jest:
      uris[0]: http://172.31.51.59:9200
      uris[1]: http://172.31.51.250:9200
      read-timeout: 20000
      connection-timeout: 20000
      username: esearch-ai-aws
      password: a@ss&2@1aaAQ
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-dimensions_gb_recommend
    producer:
      client-id: bts-gb-log
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092


app:
  kafka:
    log-source-topic: glbg-analitic
    gb-good-detail-rec-topic: dy_bts_gb_gd_rec_report
  hbase:
    gb-cookie-userid-table: dy_gb_cookie_userid_rel
    gb-cookie-user-clumn-family: cookie_userid
  redis:
    gb-adt-expired-seconds: 1209600

server:
  port: 38087