package com.globalegrow.model.bts;

import java.util.Date;

public class BtsResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.result_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Long resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.plan_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Long planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.plan_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String planCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.plan_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.plan_status
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Byte planStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.product_line_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String productLineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.cookie
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.bucket_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Byte bucketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.recormand_type
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String recormandType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.version_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Long versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.version_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String versionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.version_flag
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private String versionFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.creator
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bts_plan_result.create_time
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.result_id
     *
     * @return the value of b_bts_plan_result.result_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Long getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.result_id
     *
     * @param resultId the value for b_bts_plan_result.result_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.plan_id
     *
     * @return the value of b_bts_plan_result.plan_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.plan_id
     *
     * @param planId the value for b_bts_plan_result.plan_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.plan_code
     *
     * @return the value of b_bts_plan_result.plan_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getPlanCode() {
        return planCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.plan_code
     *
     * @param planCode the value for b_bts_plan_result.plan_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setPlanCode(String planCode) {
        this.planCode = planCode == null ? null : planCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.plan_name
     *
     * @return the value of b_bts_plan_result.plan_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.plan_name
     *
     * @param planName the value for b_bts_plan_result.plan_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.plan_status
     *
     * @return the value of b_bts_plan_result.plan_status
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Byte getPlanStatus() {
        return planStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.plan_status
     *
     * @param planStatus the value for b_bts_plan_result.plan_status
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setPlanStatus(Byte planStatus) {
        this.planStatus = planStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.product_line_code
     *
     * @return the value of b_bts_plan_result.product_line_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getProductLineCode() {
        return productLineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.product_line_code
     *
     * @param productLineCode the value for b_bts_plan_result.product_line_code
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setProductLineCode(String productLineCode) {
        this.productLineCode = productLineCode == null ? null : productLineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.cookie
     *
     * @return the value of b_bts_plan_result.cookie
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.cookie
     *
     * @param cookie the value for b_bts_plan_result.cookie
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.bucket_id
     *
     * @return the value of b_bts_plan_result.bucket_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Byte getBucketId() {
        return bucketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.bucket_id
     *
     * @param bucketId the value for b_bts_plan_result.bucket_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setBucketId(Byte bucketId) {
        this.bucketId = bucketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.recormand_type
     *
     * @return the value of b_bts_plan_result.recormand_type
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getRecormandType() {
        return recormandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.recormand_type
     *
     * @param recormandType the value for b_bts_plan_result.recormand_type
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setRecormandType(String recormandType) {
        this.recormandType = recormandType == null ? null : recormandType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.version_id
     *
     * @return the value of b_bts_plan_result.version_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.version_id
     *
     * @param versionId the value for b_bts_plan_result.version_id
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.version_name
     *
     * @return the value of b_bts_plan_result.version_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.version_name
     *
     * @param versionName the value for b_bts_plan_result.version_name
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.version_flag
     *
     * @return the value of b_bts_plan_result.version_flag
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public String getVersionFlag() {
        return versionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.version_flag
     *
     * @param versionFlag the value for b_bts_plan_result.version_flag
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setVersionFlag(String versionFlag) {
        this.versionFlag = versionFlag == null ? null : versionFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.creator
     *
     * @return the value of b_bts_plan_result.creator
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.creator
     *
     * @param creator the value for b_bts_plan_result.creator
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bts_plan_result.create_time
     *
     * @return the value of b_bts_plan_result.create_time
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bts_plan_result.create_time
     *
     * @param createTime the value for b_bts_plan_result.create_time
     *
     * @mbg.generated Fri Jul 13 18:10:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}