spring:
  profiles:
    active: @profiles.active@
logging:
  config: classpath:logback-spring.xml
  path: logs
  file: bts-info-query.log
  level:
    root: info
    org.springframework: ERROR

---
spring:
  profiles: test
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-dimensions_zafu_recommend
    producer:
      client-id: bts-rg-log
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092


app:
  kafka:
    log-source-topic: dy_zaful_bury_source_data
    rg:
      cart:
        topic: bts_rg_cart_report

---
spring:
  profiles: prod
  redis:
    timeout: 86400
    password: 6e1KWyC29w
    sentinel:
      master: sentinel-172.31.42.160-6383
      nodes: 172.31.34.55:6384,172.31.42.160:6384,172.31.54.133:6383
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bts-log-rg-cart-report
    producer:
      client-id: bts-rg-log
    bootstrap-servers: 172.31.35.194:9092,172.31.50.250:9092,172.31.63.112:9092
    listener:
      concurrency: 10


app:
  kafka:
    log-source-topic: glbg-analitic
    rg:
      cart:
        topic: bts_rg_cart_report

server:
  port: 38088