package com.globalegrow.dy.mapper;

import com.globalegrow.dy.model.BtsReportFieldConfig;
import com.globalegrow.dy.model.BtsReportFieldConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtsReportFieldConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    long countByExample(BtsReportFieldConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int deleteByExample(BtsReportFieldConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int insert(BtsReportFieldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int insertSelective(BtsReportFieldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    List<BtsReportFieldConfig> selectByExample(BtsReportFieldConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    BtsReportFieldConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") BtsReportFieldConfig record, @Param("example") BtsReportFieldConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int updateByExample(@Param("record") BtsReportFieldConfig record, @Param("example") BtsReportFieldConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int updateByPrimaryKeySelective(BtsReportFieldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DY_BTS_REPORT_FIELD_CONFIG
     *
     * @mbg.generated Thu Aug 23 15:29:56 CST 2018
     */
    int updateByPrimaryKey(BtsReportFieldConfig record);
}