package com.globalegrow.dy.mapper;

import com.globalegrow.dy.model.DyReportKylinConfig;
import com.globalegrow.dy.model.DyReportKylinConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DyReportKylinConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    long countByExample(DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int deleteByExample(DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int insert(DyReportKylinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int insertSelective(DyReportKylinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    List<DyReportKylinConfig> selectByExampleWithBLOBs(DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    List<DyReportKylinConfig> selectByExample(DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    DyReportKylinConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") DyReportKylinConfig record, @Param("example") DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DyReportKylinConfig record, @Param("example") DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByExample(@Param("record") DyReportKylinConfig record, @Param("example") DyReportKylinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByPrimaryKeySelective(DyReportKylinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DyReportKylinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_report_kylin_config
     *
     * @mbg.generated Thu Dec 27 18:37:39 CST 2018
     */
    int updateByPrimaryKey(DyReportKylinConfig record);
}